### ISSUE TITLE
import multiple builddefinitions at once

### ISSUE THREAD

**Issue by lemoinek** [onlyutkarsh/ExportImportBuildDefinition#1]
### Installed product versions
- Export/Import Buid Definition extension: 0.0.1
### Description

It would be nice that you can import multiple builddefinitions at once
### Current behavior

only 1 builddefinition can be imported

**Comment by onlyutkarsh** [comment]
@lemoinek Thanks for the suggestion! Great idea, I have added it to the backlog. As you can imagine, the validation and error handling (when creating multiple definitions at once) becomes very critical in this scenario and I would love to implement this when SDK and API are stable.
