### ISSUE TITLE
Extension manifest file format is invalid

### ISSUE THREAD

**Issue by PavelShyshkouski** [onlyutkarsh/ExportImportBuildDefinition#10]
### Installed product versions
- Microsoft Visual Studio Team Foundation Server: 14.0.24606.0
- Export/Import Buid Definition extension: 0.0.2

### Description
Attempts to install the extension on TFS 2015 fail with the following error:
"Extension manifest file format is invalid".

### Steps to recreate
1. Download Export/Import Build Definition for Team Foundation Server version 0.0.2.
2. Open Control panel - Extensions using admin account in TFS 14.0.24606.0.
The url is http://<server>:8080/tfs/_admin/_extensions
3. Press "Install" button.
4. Select Export/Import Build Definition .vsix file using "Choose file" button.
5. Press "Ok".

### Current behavior
The following message is shown:
"Extension manifest file format is invalid".
Installation can't be completed.

### Expected behavior
The extension should be installed normally or instructions about how to get around the problem are provided.

**Comment by onlyutkarsh** [comment]
@PavelShyshkouski It seems you are trying this extension on TFS 2015 Update 1. Extensions were only introduced from [TFS 2015 Update 2](https://www.visualstudio.com/en-us/news/releasenotes/tfs2015-update2-vs) onward. Can you please update TFS 2015 to minimum Update 2 and then try?

Detailed steps on how to install extension are here: https://www.visualstudio.com/en-us/docs/marketplace/get-vsts-extensions
