### ISSUE TITLE
TFS.WebApi.Exception - Resource not availible for anonymous access

### ISSUE THREAD

**Issue by larserikfinholt** [onlyutkarsh/ExportImportBuildDefinition#11]
### Installed product versions
- Export/Import Buid Definition extension: 0.0.2 and TFS2017

### Description
Unable to export. After clicking on Export from context menu, a alert pops up With the text: TFS.WebApi.Exception - Resource not availible for anonymous Access. Client Authenticatio requireed

### Steps to recreate
1. Click on export from context menu

### Current behavior
a alert pops up With the text: TFS.WebApi.Exception - Resource not availible for anonymous Access. Client Authenticatio requireed

### Expected behavior
Anything but an error

**Comment by onlyutkarsh** [comment]
@larserikfinholt thanks, I will take a look. Meanwhile can you please paste/share screenshot if you see any errors in the console window (of google chrome)?

**Comment by larserikfinholt** [comment]
Sure
![image](https://cloud.githubusercontent.com/assets/1328417/20889630/ea70c57e-bb03-11e6-88ad-90461f54167b.png)

**Comment by onlyutkarsh** [comment]
Thanks @larserikfinholt I will take a look.

**Comment by onlyutkarsh** [comment]
@larserikfinholt sorry for the delay in fixing this. The latest version of the extension should fix this issue. Please try and let me know.
