### ISSUE TITLE
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products on  Foudation 2015 installed on my Windows Server  R2

### ISSUE THREAD

**Issue by jruiviana** [onlyutkarsh/ExportImportBuildDefinition#12]
### Installed product versions
- Export/Import Buid Definition extension: [example 1.1.21]

### Description
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products on  Foudation 2015 installed on my Windows Server  R2

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
I have  Team foudation 2015 installed on Windows server 2012 R2 I´m getting a error  on the intallation.

See the log below:

1/26/2017 8:46:47 AM - Microsoft VSIX Installer
1/26/2017 8:46:47 AM - -------------------------------------------
1/26/2017 8:46:47 AM - Initializing Install...
1/26/2017 8:46:47 AM - Extension Details...
1/26/2017 8:46:47 AM - 	Identifier         : ExportImportBuildDefinition
1/26/2017 8:46:47 AM - 	Name               : Export/Import Build Definition
1/26/2017 8:46:47 AM - 	Author             : onlyutkarsh
1/26/2017 8:46:47 AM - 	Version            : 0.0.2
1/26/2017 8:46:47 AM - 	Description        : Export/Import your build definitions. Useful for recreating all the build steps, variables, schedules, etc in a different team project.
1/26/2017 8:46:47 AM - 	Locale             : en-US
1/26/2017 8:46:47 AM - 	MoreInfoURL        : 
1/26/2017 8:46:47 AM - 	InstalledByMSI     : False
1/26/2017 8:46:47 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
1/26/2017 8:46:47 AM - 
1/26/2017 8:46:47 AM - 	SignatureState     : Unsigned
1/26/2017 8:46:47 AM - 	Supported Products : 
1/26/2017 8:46:47 AM - 		Microsoft.VisualStudio.Services
1/26/2017 8:46:47 AM - 			Version : 
1/26/2017 8:46:47 AM - 
1/26/2017 8:46:47 AM - 	References         : 
1/26/2017 8:46:47 AM - Signature Details...
1/26/2017 8:46:47 AM - 	Extension is not signed.
1/26/2017 8:46:47 AM - 
1/26/2017 8:46:47 AM - Searching for applicable products...
1/26/2017 8:46:47 AM - Found installed product - Microsoft Visual Studio Professional 2015
1/26/2017 8:46:47 AM - Found installed product - Microsoft Visual Studio Community 2015
1/26/2017 8:46:47 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
1/26/2017 8:46:47 AM - Found installed product - Global Location
1/26/2017 8:46:47 AM - Found installed product - ssms
1/26/2017 8:46:47 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

### Expected behavior
Install the extension on Team foudation 2015

**Comment by onlyutkarsh** [comment]
Hello @jruiviana. Looks like you have double clicked the vsix file. To install the extension, go to this [link](https://www.visualstudio.com/en-us/docs/marketplace/get-tfs-extensions#disconnected-tfs) and follow the steps mentioned. Also note that extensions are supported only on TFS 2015 Update 3 on wards.
