### ISSUE TITLE
Unable to Import - TFS.WebApi.Exception: TF400813

### ISSUE THREAD

**Issue by PaulMatthewMadden** [onlyutkarsh/ExportImportBuildDefinition#17]
### Installed product versions
- Export/Import Buid Definition extension: 0.0.8

### Description
Export seems to work fine.  Importing gives me the following error (same Collection and same Team Project):

"Unable to parse the uploaded JSON due to error TFS.WebApi.Exception: TF400813: Resource not available for anonymous access. Client authentication required."

I am using TFS 2017 (15.105.25910.0).  My TFS website is HTTP.  My user account is part of the Project Collection Administrators security group.  Same result on IE, Edge, and Chrome.

I notice when I install the extension it asks for the following permissions:

- Agent Pools (read)
- Build (read and execute)
- Build (read)

Shouldn't there be some 'write' permissions for importing?

Looks like a great extension when working!  I would love to be able to use it!  Thanks!

![tfs 2017 import export build def install](https://cloud.githubusercontent.com/assets/4973504/23873456/17085266-0800-11e7-9a7e-5013c954d503.png)

![tfs 2017 import export build def error](https://cloud.githubusercontent.com/assets/4973504/23873455/170642fa-0800-11e7-9806-4c209926fb40.png)

**Comment by onlyutkarsh** [comment]
@PaulMatthewMadden Thanks for the feedback. Looks like you are on TFS 2017 RTM version. The `vso.agentpools` scope is available only from Update1 RC2 onwards. So installing [TFS 2017 Update 1](https://blogs.msdn.microsoft.com/bharry/2017/03/08/team-foundation-server-2017-update-1-available/) should resolve the issue. See #16 where we discussed the same.

regarding your question _Shouldn't there be some 'write' permissions for importing?_
Yes, write permission for creating the definition, but `vso.build_execute` covers that. 
- Scopes for extension read/create definition (`vso.build_execute` and `vso.build`)
- Read build queues and pools (`vso.agentpools`) - no need of write permissions.

If you are interested, more details on scopes is [here](https://www.visualstudio.com/en-us/docs/integrate/extensions/develop/manifest#scopes)

**Comment by onlyutkarsh** [comment]
@PaulMatthewMadden I am closing the issue. Please let me know if the issue still exists even after installing TFS 2017 Update 1.

**Comment by PaulMatthewMadden** [comment]
Thank you very much!  That all makes sense now.  I appreciate your quick response!  I will let you know if I have further problems.
