### ISSUE TITLE
Unable to parse the uploaded JSON due to error TFS.Web Api.Exception

### ISSUE THREAD

**Issue by NagalaJ** [onlyutkarsh/ExportImportBuildDefinition#19]
### Installed product versions
- Export/Import Buid Definition extension: Version 0.0.8 

### Description
Unable to parse the uploaded JSON due to error TFS.Web Api.Exception

### Steps to recreate
1. Tried the Import option on an existing build definition
2. When trying to upload a json file, we received an error 

### Error
Unable to parse the uploaded JSON due to error TFS.Web Api.Exception: Tfs400813: resource not available for anonymous access. Client authentication required

**Comment by onlyutkarsh** [comment]
Please see #17.
