### ISSUE TITLE
"Scope is not Valid" Error

### ISSUE THREAD

**Issue by brett3210** [onlyutkarsh/ExportImportBuildDefinition#27]
### Installed product versions
- Export/Import Build Definition extension: 0.0.8

### Description
Received the error "Scope is not valid: 'vso.agentpools'"

### Steps to recreate
1. Downloaded older v0.0.2 as per https://marketplace.visualstudio.com/items?itemName=onlyutkarsh.ExportImportBuildDefinition#review-details
2. Imported it to TFS 2015 Update 3

### Current behavior
Received error "Scope is not valid: 'vso.agentpools'".
Import/Export menu item doesn't appear in Chrome

### Expected behavior
No error

**Comment by onlyutkarsh** [comment]
Please see my response to similar issue #17 - You need to install the older version of this extension.

**Comment by brett3210** [comment]
Thanks, however I can't seem to find a specific reference to an older version in the Issue you've referred to.  As per my Issue, I used the older v0.0.2 version.  Can you please clarify?

**Comment by onlyutkarsh** [comment]
Yes, you should use v0.0.2. The `vso.agentpools` scope is available only from Update1 RC2 onwards only. If the upgrade is not feasible for you, you should use the older [0.0.2 version](https://github.com/onlyutkarsh/ExportImportBuildDefinition/releases/tag/v0.0.2) which unfortunately lacks few features.

**Comment by brett3210** [comment]
Thanks, however we have already installed v0.0.2 of the Extension, with TFS 2015 Update 3, with the errors mentioned.  Can you please clarify how we can get it working?

**Comment by onlyutkarsh** [comment]
@brett3210 That seems to be weird. If you see 0.0.2's manifest file you will see the only scopes it requires are as 
```json
"scopes": [
        "vso.build_execute",
        "vso.build"
    ],
```
I am really not getting how the v0.0.2 of the extension can demand `vso.agentpools`. Can you please share the VSIX file you using?

**Comment by brett3210** [comment]
I've tried again and it is working now thanks

**Comment by onlyutkarsh** [comment]
Glad you got it working! thanks.
