### ISSUE TITLE
Won't install on Visual Studio Enterprise 2017 (Version 15.4.3)

### ISSUE THREAD

**Issue by tuyenqh** [onlyutkarsh/ExportImportBuildDefinition#28]
### Installed product versions
- Export/Import Buid Definition extension: 0.0.8

### Description
Won't install for TFS 2017 Update 2

### Steps to recreate
1. Download onlyutkarsh.ExportImportBuildDefinition-0.0.8.vsix
2. Double-click on onlyutkarsh.ExportImportBuildDefinition-0.0.8.vsix

### Current behavior
A pop-up occurs saying "This extension is not installable on any currently installed products"
The contents of the log file:
09-11-2017 15:47:22 - Microsoft VSIX Installer
09-11-2017 15:47:22 - -------------------------------------------
09-11-2017 15:47:22 - vsixinstaller.exe version:
09-11-2017 15:47:22 - 15.0.437+g8d2477ee3d
09-11-2017 15:47:22 - -------------------------------------------
09-11-2017 15:47:22 - Command line parameters:
09-11-2017 15:47:22 - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\tqhoang\Downloads\onlyutkarsh.ExportImportBuildDefinition-0.0.8.vsix
09-11-2017 15:47:22 - -------------------------------------------
09-11-2017 15:47:22 - Microsoft VSIX Installer
09-11-2017 15:47:22 - -------------------------------------------
09-11-2017 15:47:22 - Initializing Install...
09-11-2017 15:47:23 - Extension Details...
09-11-2017 15:47:23 - 	Identifier         : ExportImportBuildDefinition
09-11-2017 15:47:23 - 	Name               : Export/Import Build Definition
09-11-2017 15:47:23 - 	Author             : onlyutkarsh
09-11-2017 15:47:23 - 	Version            : 0.0.8
09-11-2017 15:47:23 - 	Description        : Export and Import your build definitions. Useful for recreating all the build steps, variables, schedules, etc in a different team project.
09-11-2017 15:47:23 - 	Locale             : en-US
09-11-2017 15:47:23 - 	MoreInfoURL        : 
09-11-2017 15:47:23 - 	InstalledByMSI     : False
09-11-2017 15:47:23 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
09-11-2017 15:47:23 - 
09-11-2017 15:47:23 - 	SignatureState     : Unsigned
09-11-2017 15:47:23 - 	Supported Products : 
09-11-2017 15:47:23 - 		Microsoft.VisualStudio.Services
09-11-2017 15:47:23 - 			Version : 
09-11-2017 15:47:23 - 
09-11-2017 15:47:23 - 	References         : 
09-11-2017 15:47:23 - Signature Details...
09-11-2017 15:47:23 - 	Extension is not signed.
09-11-2017 15:47:23 - 
09-11-2017 15:47:23 - Searching for applicable products...
09-11-2017 15:47:23 - Found installed product - Microsoft Visual Studio 2010 Professional
09-11-2017 15:47:23 - Found installed product - Microsoft Visual Studio Premium 2013 
09-11-2017 15:47:23 - Found installed product - Microsoft Visual Studio Professional 2013
09-11-2017 15:47:23 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
09-11-2017 15:47:23 - Found installed product - Global Location
09-11-2017 15:47:23 - Found installed product - Visual Studio Enterprise 2017
09-11-2017 15:47:23 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

### Expected behavior
Should install sucessfully

**Comment by nschonni** [comment]
This is an extension for TFS, but it seems like you're trying to install it into a Visual Studio instance.
https://docs.microsoft.com/en-us/vsts/marketplace/get-tfs-extensions

**Comment by tuyenqh** [comment]
You are right. My mistake, I only saw what I wanted to see. Sorry and thank you for pointing it out.
