### ISSUE TITLE
Export/Import with Secret Variable issue with V2.x agents

### ISSUE THREAD

**Issue by Mailhot01** [onlyutkarsh/ExportImportBuildDefinition#29]
### Installed product versions
- Export/Import Buid Definition extension 0.02

### Description
Created a build definition by importing a template.
Build on a V1.x agent and a V2.x agent.
The V2.x agent builds log show that secret variables passed to scripts are empty.

### Steps to recreate
1. Make sure you build agent is v2.x
2. Create a new build definition
3. Add a Secret Variable named Password
4. Pass the secret variable to a script using $(Password)
5. build and verify that the secret variable was passed
6. Export the build definition
7. Import to a new build definition
8. build and verify that the secret variable was passed properly 
(FAIL, secret variable empty)

### Current behavior
We noted that secret variable were not working for all build definition which we imported from a saved template.  The build definition actually shows the secret variable properly, but the end results show that the script only get empty strings.

### Expected behavior
Secret Variable should work the same as the original build definition

**Comment by onlyutkarsh** [comment]
Hey @Mailhot01 

Secret variables are:
- Encrypted at rest with a 2048-bit RSA key.
- **Not returned back to the client.** They are automatically masked out of any log output from the build or release.
- Not decrypted into environment variables. So scripts and programs run by your build steps are not given access by default.
- Decrypted for access by your build steps. So you can use them in password arguments and also pass them explicitly into a script or a program from your build step (for example as $(password)).

Hence they are not available for any extensions or tasks to read the value. So this cannot be supported by the extension.

**Comment by Mailhot01** [comment]
Thank you for the quick reply,

Your explanation makes perfect sens in that's it is not an issue but a desired limitation.

But in the end,  once imported,  the secret variable IS present and looks ok.
Maybe the import should discard any secret variable and put empty its value field ?

For anyone else interested in this report,  know that you simply have to manually delete and recreate the secret variable after the import.  

Thank you for the plug-in, it certainly saved us some time by deploying 200+ build def.
