### ISSUE TITLE
The export/import menu items don't show up on the new build panels

### ISSUE THREAD

**Issue by jessehouwing** [onlyutkarsh/ExportImportBuildDefinition#4]
### Installed product versions
- Export/Import Buid Definition extension: [example 1.1.21]

### Description
Picture says more than a thousand words:

![image](https://cloud.githubusercontent.com/assets/4173387/16990349/04017de0-4e98-11e6-93d3-e24fbe428f6c.png)

On the same account it does show up on the "old build explorer"

![image](https://cloud.githubusercontent.com/assets/4173387/16990393/26df998c-4e98-11e6-861c-6b89fcaad0ed.png)

**Comment by onlyutkarsh** [comment]
@jessehouwing thanks, Jesse, I am aware of this issue. Unfortunately, there are no contribution points available as of now for the new build hub. I will definitely add the menu items once extension points are exposed.

**Comment by rrober07** [comment]
Even when I add a new Build Def it still not showing up...it did before with Update 2....we are using Update 3...so it is broke again.  I was counting on this tool to help me...now I have to plan for the worst...I have over 50 projects and don't want to manually create when I bring over our production collection.  TFS15 suposeably will have this feature baked in...by that time it won't be of that much help... any tips or suggestions?

**Comment by rrober07** [comment]
I have resolved my issue...it was a server issues...all is well

**Comment by onlyutkarsh** [comment]
@jessehouwing this is fixed in VSTS now.

**Comment by onlyutkarsh** [comment]
@rrober07 Glad the issue is resolved for you. :-)

**Comment by rrober07** [comment]
So you have an update for your extension?

**Comment by onlyutkarsh** [comment]
@rrober07 No, this was fixed by product team. The issue was that extensions did not get the correct context from SDK, once it was fixed extension worked automatically.

**Comment by brett3210** [comment]
Hi.  Unfortunately, this issue has reappeared again. The menu is not showing up in VSTS under the Build and Explorer tabs
